
[main]
# Interval is 30 seconds
triggers = "after cinderella @delay 5"
name = "Hpge"


# action.main 是一个执行序列的第一个action
[action.main]
type = "mysql_select"
next = "post"
datasource="mysql1"

[action.post]
type = "http_send"
url = "http://127.0.0.1:1024/d/send"
next = ""