
[main]
# Interval is 30 seconds
name = "cinderella"
require = ["cinderella.sub.toml"]

# every-min 00 30
triggers = ["every-minute 05", "every-minute 25", "every-minute 35", "every-minute 55"]

[vars]
offset_seconds = 5
b = ["1", "hello"]

[logger.me]
filename="cind-{$date}.log"
path="/Users/healer/{$month}"


# action.main 是一个执行序列的第一个action
[action.main]
type = "mysql_select"
mysqlconnection="mysqlconnection"
sql = "select * from z_cinderella_rec where time=from_unixtime({$current_seconds} - {@@offset_seconds});"
next = "transform"
return = "result_set"
logto = "me"
loglevel = 1

# Goto sub toml



