

[main]
name = "cinderella.history"

# 每分钟尝试获取一次历史数据命令
triggers = ["every-minute 00"]
require = ["cinderella.sub.toml"]


# action.main 是一个执行序列的第一个action
[action.main]
type = "http_get"
url = "http://127.0.0.1:1024/d/cmd/history/{$cinderella_device_id}"
return_json = "lost_data"
next = "selectlost"
exit_at = "{@lost_data.status} != 0"

[action.selectlost]
type = "mysql_select"
mysqlconnection="mysqlconnection"
# TODO: 优化UNIX_TIMESTAMP, 现在用不到Time字段的索引了
sql = "select * from z_cinderella_rec where UNIX_TIMESTAMP(time) in ({@lost_data.data.list|stringify|join});"
next = "transform"
return = "result_set"





