
[main]
name = "cinderella.realtime"

# 每个30秒, 00秒(归一化时间)后的5秒尝试发送数据
triggers = ["every-minute 05", "every-minute 25", "every-minute 35", "every-minute 55"]

require = ["cinderella.sub.toml"]

[vars]
offset_seconds = 5


[logger.me]
filename="cind-{$date}.log"
path="/Users/healer/{$month}"


# action.main 是一个执行序列的第一个action
[action.main]
type = "mysql_select"
mysqlconnection="mysqlconnection"
sql = "select * from z_cinderella_rec where time=from_unixtime({$current_seconds} - {@@offset_seconds});"
next = "transform"
return = "result_set"
exit_at = "len({@result_set}) == 0"
logto = "me"
loglevel = 1




