

[main]
# Interval is 30 seconds
name = "cinderella"

# every-min 00 30
triggers= ["every-minute 05", "every-minute 15", "every-minute 05", "every-minute 28", "every-minute 35", "every-minute 50"]

[logger.me]
filename="cind-{$date}.log"
path="/Users/healer/{$month}"


# action.main 是一个执行序列的第一个action
[action.main]
type = "mysql_select"
mysqlconnection="mysqlconnection"
sql = "select * from z_cinderella_rec"
next = "transform"

[action.transform]
type = "resultset_to_form"
key_value_attributes = [
    ["PressureDiff", "pressureDiff", ""],
    ["Pressure", "pressure", ""],
    ["Temperature", "temperature", ""],
    ["FlowPerHour", "flowPerHour", ""],
    ["Flow", "flow", ""],
    ["Worktime", "workTime", ""],
    ["BeginTime", "beginTime", "unixtime"],
    ["Barcode", "barcode", ""],
    ["Sid", "sid", ""],
    ["Time", "dataTime", "unixtime"],
    ]
input = "$"
output = "$"
next = "post"

[action.post]
type = "http_post"
url = "http://127.0.0.1:1024/d/send/2"
data = "$"
next = ""



