

[action.requestBatchProductInfo]
type = "http.get"
url = "d"
next = "b"
start_at = ""

[action.b]
value = 1
next = "c"


[action.requestBatchSkuInfo]
type = "http.get"
url = "d"
next = "c"
start_at = ""

