

[action.requestBatchProductInfo]
type = "http.get"
log = "a.log"
url = "d"
next = "b"
start_at = ""
trigger = "cron"
seconds = "*/5"

[action.b]
value = 1
next = "c"


[action.requestBatchSkuInfo]
type = "http.get"
url = "d"
next = "c"
start_at = ""
log = "b.log"
trigger = "cron"
seconds = "*/10"


