

[action.requestBatchProductInfo]
type = "http.get"
log = "a.log"
url = "http://127.0.0.1:9090/api/kxusers"
next = "b"
start_at = ""
trigger = "cron"
second = "*/5"

[action.b]
type = "json.check"
value = 1
next = "c"


[action.requestBatchSkuInfo]
type = "http.get"
url = "http://127.0.0.1:9090/api/kxusers"
next = "c"
start_at = ""
log = "b.log"
trigger = "cron"
minute = "*/2"


