

[main]
# Interval is 30 seconds
name = "cinderella"

# every-min 00 30
triggers= ["every-minute 05", "every-minute 35"]

[datasource]
type="mysql"


# action.main 是一个执行序列的第一个action
[action.main]
type = "mysql_select"
mysqlconnection="mysqlconnection"
next = "post"
datasource="mysql1"

[action.post]
type = "http_send"
url = "http://127.0.0.1:1024/d/send"
next = ""



